# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: 
date_format: "ordinal"
title: 中国科学技术大学学生业余无线电协会
# subtitle: "公众号：闷骚的程序员"
# description: "马壮的个人博客，公众号：闷骚的程序员"
keywords: 中国科学技术大学, 业余无线电, BY6DX
timezone: Asia/Shanghai
encoding: "utf-8"
# repository: mzlogin/mzlogin.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false

# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: BY6DX
organization: 
organization_url: 
github_username: BY6DX
callsign: BY6DX
location: "CQ: 24 &nbsp;&nbsp; ITU: 44 &nbsp;&nbsp; Grid: OM81pu &nbsp;&nbsp; QTH: Hefei, Anhui, China"
email: radio@ustc.edu.cn
logo: assets/images/by6dx.png

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /about/
    label: 关于

  -
    href: /old/
    label: 旧版网站

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:title.html
plugins:
#     - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: false
        permalink: /wiki/:path/

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10
