name: Build and Deploy

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Set Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install and Build
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build --baseurl /by6dx
        
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.qsl.net
          username: by6dx
          password: ${{ secrets.QSL_NET_PWD }}
          local-dir: ./_site/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            /old/**
